version: "3.9"
services:
  gigalixir:
    build: docker/gigalixir
    profiles: ["cli"]
    volumes:
      - .:/app
      - ./docker/gigalixir:/root
    working_dir: /app
    entrypoint: gigalixir
  phoenix:
    build:
      context: .
      dockerfile: docker/phoenix/Dockerfile
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: card_game_alpha_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
